export const CANDIDATE_NAME = 'Candidate Name'
export const CLIENT_NAME = 'Client Name'
export const JOB_TITLE = 'Job Title'
export const START_DATE = 'Start Date'
export const END_DATE = 'End Date'
export const PLACEMENT_TYPE = 'Placement Type'